# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-11-05 20:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0001_initial'),
        ('mascotas', '0002_auto_20181105_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopciones.Persona'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='fecha_rescate',
            field=models.DateField(default=datetime.datetime(2018, 11, 5, 20, 28, 20, 2348, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='mascota',
            name='vacuna',
            field=models.ManyToManyField(to='mascotas.Vacuna'),
        ),
    ]
