# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-11-05 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_auto_20181105_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='vacuna',
            field=models.ManyToManyField(blank=True, to='mascotas.Vacuna'),
        ),
    ]
